version: "3"
services:
    laravel:
        image: lorisleiva/laravel-docker:7.4
        container_name: vue-reflection-laravel
        volumes:
            - .:/var/www
        working_dir: /var/www
        ports:
            - 8004:8000
        command: [sh, -c, "
            touch database/database.sqlite database/test.sqlite
            && composer install
            && cd public
            && php -S 0.0.0.0:8000
        "]
    vue:
        image: node:16
        container_name: vue-reflection-vue
        volumes:
            - .:/app
        working_dir: /app
        command: [sh, -c, "
            npm install
            && npm run watch
        "]
